SWEAR_WORDS_ARRAY: [блять, блядь, бляди, ебать, ёб, бля, блядина, блядский, блядистость, блядогон,
  блядословник, блядский, блядство, въебаться, взбляд, впиздячил, выблядовал, выблядок,
  выебон, выёбывается, глупизди, доебался, ебанёшься, ебанул, ебашит, ёбнул, ебало,
  ебанулся, ебнул, жидоёб, жидоёбский, заёб, изъебнулся, заебал, заебись, козлоёб,
  козлоёбище, хуй, пизда, пиздец, \*, сука]

PRONOUNS_ARRAY: ['ты', 'Ты', 'и', 'И', 'я', 'Я', 'в', 'не', 'Не', 'что', 'на', 'но',
  'с', 'как', 'это', 'а', 'А', 'Но', 'У', 'он', 'Он', '-', '–', 'Так', 'У', 'у', 'За',
  'за', 'Эй', 'то', 'по', 'бы', 'тебе', 'мой', 'же', 'его', 'мы', 'от', 'ведь', 'Ведь',
  'где', 'Где', 'про', 'к', 'В', 'до', 'чем', 'еще', 'о', 'без', 'Мы', '—', ' ']
